// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Sign Request
---
*/
package cmds

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path"

	"github.com/365admin/koksmat-sign/execution"
	"github.com/365admin/koksmat-sign/schemas"
	"github.com/365admin/koksmat-sign/utils"
)

func Sign10Signps1Post(ctx context.Context, body []byte, args []string) (*schemas.SignedRequest, error) {
	inputErr := os.WriteFile(path.Join(utils.WorkDir("koksmat-sign"), "request.json"), body, 0644)
	if inputErr != nil {
		return nil, inputErr
	}

	result, pwsherr := execution.ExecutePowerShell("john", "*", "koksmat-sign", "20-sign", "10-sign.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}

	resultingFile := path.Join(utils.WorkDir("koksmat-sign"), "signed-request.json")
	data, err := os.ReadFile(resultingFile)
	if err != nil {
		return nil, err
	}
	resultObject := schemas.SignedRequest{}
	err = json.Unmarshal(data, &resultObject)
	if utils.Output == "json" {
		fmt.Println(string(data))
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))

	return nil, nil

}
