// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Sign Request
---
*/
package endpoints

import (
	"context"
	"encoding/json"
	"os"
	"path"

	"github.com/swaggest/usecase"

	"github.com/365admin/koksmat-sign/execution"
	"github.com/365admin/koksmat-sign/schemas"
	"github.com/365admin/koksmat-sign/utils"
)

func Sign10Signps1Post() usecase.Interactor {
	type Request struct {
		Body schemas.Request `json:"body" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *schemas.SignedRequest) error {
		body, inputErr := json.Marshal(input.Body)
		if inputErr != nil {
			return inputErr
		}

		inputErr = os.WriteFile(path.Join(utils.WorkDir("koksmat-sign"), "request.json"), body, 0644)
		if inputErr != nil {
			return inputErr
		}

		_, err := execution.ExecutePowerShell("john", "*", "koksmat-sign", "20-sign", "10-sign.ps1", "")
		if err != nil {
			return err
		}

		resultingFile := path.Join(utils.WorkDir("koksmat-sign"), "signed-request.json")
		data, err := os.ReadFile(resultingFile)
		if err != nil {
			return err
		}
		resultObject := schemas.SignedRequest{}
		err = json.Unmarshal(data, &resultObject)
		*output = resultObject
		return err

	})
	u.SetTitle("Sign Request")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("20-sign")
	return u
}
